### ISSUE TITLE
Docs: Tutorial page contains some git operation log

### ISSUE THREAD

**Issue by stu01509** [reactjs/zh-hant.reactjs.org#275]
Docs: Tutorial page contains some git operation log, If it is an issue, I would like to solve it :)
https://zh-hant.reactjs.org/tutorial/tutorial.html

![image](https://user-images.githubusercontent.com/22230889/151807060-485fbe88-6bcd-4f50-b6b7-1d6a8c42789d.png)

**Comment by neighborhood999** [comment]
> Docs: Tutorial page contains some git operation log, If it is an issue, I would like to solve it :) [zh-hant.reactjs.org/tutorial/tutorial.html](https://zh-hant.reactjs.org/tutorial/tutorial.html)
> 
> ![image](https://user-images.githubusercontent.com/22230889/151807060-485fbe88-6bcd-4f50-b6b7-1d6a8c42789d.png)

Is conflict haha, feel free to create a PR fixing, thank you.
